# Wikipedia Web Scrapping

## Anggota Kelompok
- Najla Zahira (25031554041)
- Moza Athaillah Azzahra (25031554185)

## HTTP

- Domain topik : AI, Computer Science, Data & Statistic, Technology & Internet
- Objek: Judul, URL, Overview_Isi, Tanggal_Suntingan, dan Penerbit

In [ ]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

In [ ]:
category_urls = [
    'https://id.wikipedia.org/wiki/Kategori:Komputasi',
    'https://id.wikipedia.org/wiki/Kategori:Kecerdasan_buatan',
    'https://id.wikipedia.org/wiki/Kategori:Ilmu_komputer',

    'https://id.wikipedia.org/wiki/Kategori:Pengolahan_data',
    'https://id.wikipedia.org/wiki/Kategori:Penyimpanan_data_komputer',
    'https://id.wikipedia.org/wiki/Kategori:Manajemen_data',

    'https://id.wikipedia.org/wiki/Kategori:Teknologi_informasi',
    'https://id.wikipedia.org/wiki/Kategori:Teknologi_digital',
    'https://id.wikipedia.org/wiki/Kategori:Internet'
]

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
}

semua_sukses = True
articles_list = []
seen_urls = set()

for idx, url in enumerate(category_urls, start=1):
    try:
        page = requests.get(url, headers=headers, timeout=10)

        if page.status_code == 200:
            print(f"[{idx}/{len(category_urls)}] [200]  -> {url}")

            soup = BeautifulSoup(page.text, 'html.parser')
            container = soup.find('div', id='mw-pages')
            if container:
                for link in container.find_all('a'):
                    href = link.get('href')
                    title = link.text.strip()
                    if href and href.startswith('/wiki/') and not any(p in href for p in [':', 'Istimewa', 'Halaman_Utama']):
                        full_url = 'https://id.wikipedia.org' + href
                        if full_url not in seen_urls:
                            seen_urls.add(full_url)
                            articles_list.append({'Judul': title, 'URL': full_url})
        else:
            print(f"[{idx}/{len(category_urls)}] [{page.status_code} GAGAL] -> {url}")
            semua_sukses = False

    except Exception as e:
        print(f"[{idx}/{len(category_urls)}] [ERROR] -> {url} (Detail: {e})")
        semua_sukses = False

if semua_sukses:
    print("\nSemua URL berhasil")
else:
    print("\nAda URL yang gagal.")

df_urls = pd.DataFrame(articles_list)
print(f"Total URL yang berhasil diekstrak: {len(df_urls)}")

[1/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Komputasi
[2/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Kecerdasan_buatan
[3/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Ilmu_komputer
[4/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Pengolahan_data
[5/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Penyimpanan_data_komputer
[6/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Manajemen_data
[7/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Teknologi_informasi
[8/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Teknologi_digital
[9/9] [200]  -> https://id.wikipedia.org/wiki/Kategori:Internet

Semua URL berhasil
Total URL yang berhasil diekstrak: 479

In [ ]:
scraped_data_10 = []

for idx, item in enumerate(articles_list[:10], start=1):
    url = item['URL']
    try:
        res = requests.get(url, headers=headers, timeout=10)
        if res.status_code == 200:
            soup = BeautifulSoup(res.text, 'html.parser')

            h1_title = soup.find('h1', id='firstHeading')
            title_text = h1_title.text.strip() if h1_title else item['Judul']

            last_mod = soup.find('li', id='footer-info-lastmod')
            if last_mod:
                raw_text = last_mod.text.strip()
                if 'pada ' in raw_text:
                    date_part = raw_text.split('pada ')[1]
                    clean_date = date_part.split(',')[0].strip()
                else:
                    clean_date = raw_text
            else:
                clean_date = "Tidak ditemukan"

            content_div = soup.find('div', class_='mw-parser-output')
            paragraphs = []
            if content_div:
                for p in content_div.find_all('p'):
                    text = p.text.strip()
                    if text:
                        paragraphs.append(text)

            full_overview = " ".join(paragraphs)

            scraped_data_10.append({
                'Judul': title_text,
                'URL': url,
                'Overview_Isi': full_overview,
                'Tanggal_Suntingan': clean_date,
                'Penerbit': 'Wikipedia Bahasa Indonesia'
            })
    except Exception:
        pass
    time.sleep(0.2)

print("HASIL SCRAPING 10 BARIS TERATAS:\n")
df_sample10 = pd.DataFrame(scraped_data_10)
df_sample10

HASIL SCRAPING 10 BARIS TERATAS:

,Judul,URL,Overview_Isi,Tanggal_Suntingan,Penerbit
0,Algoritma bias,https://id.wikipedia.org/wiki/Algoritma_bias,Algoritma bias menggambarkan galat sistematis ...,1 Juni 2026,Wikipedia Bahasa Indonesia
1,Algoritma Lanczos,https://id.wikipedia.org/wiki/Algoritma_Lanczos,Algoritma Lanczos adalah algoritma iteratif ad...,25 September 2026,Wikipedia Bahasa Indonesia
2,ASCII,https://id.wikipedia.org/wiki/ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia
3,Cermin (komputasi),https://id.wikipedia.org/wiki/Cermin_(komputasi),"Dalam komputasi, sebuah cermin (bahasa Inggris...",27 Mei 2024,Wikipedia Bahasa Indonesia
4,Karakter null,https://id.wikipedia.org/wiki/Karakter_null,"Karakter null (atau bita null), disingkat NUL ...",17 September 2026,Wikipedia Bahasa Indonesia
5,Karakter ujung teks,https://id.wikipedia.org/wiki/Karakter_ujung_teks,Karakter ujung teks (ETX) (nilai heksadesimaln...,26 Juni 2026,Wikipedia Bahasa Indonesia
6,ASCII,https://id.wikipedia.org/wiki/Kode_ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia
7,Kode duplikat,https://id.wikipedia.org/wiki/Kode_duplikat,Kode duplikat merupakan sumber kode yang diran...,5 April 2024,Wikipedia Bahasa Indonesia
8,Komputasi optis,https://id.wikipedia.org/wiki/Komputasi_optis,Komputasi optis adalah penggunaan foton yang d...,19 Oktober 2025,Wikipedia Bahasa Indonesia
9,LIPI Public Cluster,https://id.wikipedia.org/wiki/LIPI_Public_Cluster,LIPI Public Cluster atau LPC adalah sarana kom...,10 Februari 2026,Wikipedia Bahasa Indonesia

In [ ]:
scraped_data_all = []

for idx, item in enumerate(articles_list, start=1):
    url = item['URL']
    try:
        res = requests.get(url, headers=headers, timeout=10)
        if res.status_code == 200:
            soup = BeautifulSoup(res.text, 'html.parser')

            h1_title = soup.find('h1', id='firstHeading')
            title_text = h1_title.text.strip() if h1_title else item['Judul']

            last_mod = soup.find('li', id='footer-info-lastmod')
            if last_mod:
                raw_text = last_mod.text.strip()
                if 'pada ' in raw_text:
                    date_part = raw_text.split('pada ')[1]
                    clean_date = date_part.split(',')[0].strip()
                else:
                    clean_date = raw_text
            else:
                clean_date = "Tidak ditemukan"

            content_div = soup.find('div', class_='mw-parser-output')
            paragraphs = []
            if content_div:
                for p in content_div.find_all('p'):
                    text = p.text.strip()
                    if text:
                        paragraphs.append(text)

            full_overview = " ".join(paragraphs)

            scraped_data_all.append({
                'Judul': title_text,
                'URL': url,
                'Overview_Isi': full_overview,
                'Tanggal_Suntingan': clean_date,
                'Penerbit': 'Wikipedia Bahasa Indonesia'
            })
            print(f"[{idx}/{len(articles_list)}] Berhasil: {title_text}")

    except Exception as e:
        print(f"[{idx}/{len(articles_list)}] Gagal {url}: {e}")

    time.sleep(0.3)

df_result = pd.DataFrame(scraped_data_all)

print("\nScraping Selesai")

[1/479] Berhasil: Algoritma bias
[2/479] Berhasil: Algoritma Lanczos
[3/479] Berhasil: ASCII
[4/479] Berhasil: Cermin (komputasi)
[5/479] Berhasil: Karakter null
[6/479] Berhasil: Karakter ujung teks
[7/479] Berhasil: ASCII
[8/479] Berhasil: Kode duplikat
[9/479] Berhasil: Komputasi optis
[10/479] Berhasil: LIPI Public Cluster
[11/479] Berhasil: Membangkitkan Kombinasi
[12/479] Berhasil: Komputasi neuromorfik
[13/479] Berhasil: Teori otomata
[14/479] Berhasil: Uptime
[15/479] Berhasil: Kecerdasan buatan
[16/479] Berhasil: 2005 DARPA Grand Challenge
[17/479] Berhasil: Agen fuzzy
[18/479] Berhasil: Agen otonom
[19/479] Berhasil: Agen perangkat lunak
[20/479] Berhasil: AI Dungeon
[21/479] Berhasil: AI Love You (film 2022)
[22/479] Berhasil: AI winter
[23/479] Berhasil: AI-komplit
[24/479] Berhasil: Akinator
[25/479] Berhasil: Alat Ebert
[26/479] Berhasil: Algoritma genetik
[27/479] Berhasil: Algoritma semut
[28/479] Berhasil: Alice (asisten virtual)
[29/479] Berhasil: AlphaGo
[30/479] Berhasil: Aplikasi kecerdasan buatan untuk militer
[31/479] Berhasil: Apple Intelligence
[32/479] Berhasil: Asisten Google
[33/479] Berhasil: Brainrot Italia
[34/479] Berhasil: CarynAI
[35/479] Berhasil: Claude (model bahasa)
[36/479] Berhasil: Colossus (superkomputer)
[37/479] Berhasil: Cruel World of Dreams and Fears
[38/479] Berhasil: Dampak lingkungan dari kecerdasan buatan
[39/479] Berhasil: Deep Learning (South Park)
[40/479] Berhasil: Destination Earth
[41/479] Berhasil: Diella (sistem AI)
[42/479] Berhasil: Efek kecerdasan buatan
[43/479] Berhasil: Empati buatan
[44/479] Berhasil: Etika dalam kecerdasan buatan
[45/479] Berhasil: EU-SysFlex
[46/479] Berhasil: European High Performance Computing Joint Undertaking (EuroHPC JU)
[47/479] Berhasil: Figure AI
[48/479] Berhasil: Future of Life Institute
[49/479] Berhasil: Galaxy AI
[50/479] Berhasil: GigaChat
[51/479] Berhasil: GOLOG (bahasa pemrograman)
[52/479] Berhasil: Google AI Studio
[53/479] Berhasil: Google Klip
[54/479] Berhasil: Groupement de Recherche et d'Etudes en Gestion à HEC Paris
[55/479] Berhasil: H (perusahaan)
[56/479] Berhasil: Hak atas realitas
[57/479] Berhasil: Halusinasi (kecerdasan buatan)
[58/479] Berhasil: HEC Paris Innovation & Entrepreneurship Center
[59/479] Berhasil: Hi! PARIS
[60/479] Berhasil: Imagen (model teks-ke-gambar)
[61/479] Berhasil: Inflection AI
[62/479] Berhasil: Inisiatif Pencitraan Kanker Eropa
[63/479] Berhasil: Institut Penelitian Kecerdasan Mesin
[64/479] Berhasil: JaCoP (bahasa pemrograman)
[65/479] Berhasil: Jaringan Saraf (perangkat lunak)
[66/479] Berhasil: Jaringan saraf tiruan
[67/479] Berhasil: Kantor Kecerdasan Buatan Eropa
[68/479] Berhasil: Keamanan kecerdasan buatan
[69/479] Berhasil: Kebijaksanaan buatan
[70/479] Berhasil: Kebodohan buatan
[71/479] Berhasil: Penerapan kecerdasan buatan
[72/479] Berhasil: Kecerdasan buatan dalam fiksi
[73/479] Berhasil: Kecerdasan buatan dalam kesehatan mental
[74/479] Berhasil: Kecerdasan buatan dalam proyek-proyek Wikimedia
[75/479] Berhasil: Kecerdasan buatan dan hak cipta
[76/479] Berhasil: Kecerdasan buatan generatif
[77/479] Berhasil: Kecerdasan buatan kuantum
[78/479] Berhasil: Kecerdasan buatan simbolik
[79/479] Berhasil: Kecerdasan buatan umum
[80/479] Berhasil: Kecerdasan virtual
[81/479] Berhasil: Kecerdasan web
[82/479] Berhasil: Kedekatan buatan
[83/479] Berhasil: Kematian Elaine Herzberg
[84/479] Berhasil: Keruntuhan model
[85/479] Berhasil: Kesadaran buatan
[86/479] Berhasil: Kling AI (perusahaan)
[87/479] Berhasil: Komunitas rasionalis
[88/479] Berhasil: Kongres Keamanan Kecerdasan Buatan
[89/479] Berhasil: Kontroversi kecerdasan buatan
[90/479] Berhasil: Krisis pasokan memori global 2025-sekarang
[91/479] Berhasil: Kórsafn
[92/479] Berhasil: Lembar Jawaban Komputer
[93/479] Berhasil: Masalah pengendalian kecerdasan buatan
[94/479] Berhasil: Masyarakat 5.0
[95/479] Berhasil: Mata v. Avianca, Inc.
[96/479] Berhasil: Meta AI
[97/479] Berhasil: Microsoft Copilot
[98/479] Berhasil: Midjourney
[99/479] Berhasil: Minion (perangkat lunak)
[100/479] Berhasil: Mistisisme kecerdasan buatan
[101/479] Berhasil: Mode AI
[102/479] Berhasil: Model teks-ke-gambar
[103/479] Berhasil: Muse Spark
[104/479] Berhasil: Negosiasi otomatis
[105/479] Berhasil: OpenAI
[106/479] Berhasil: Otak buatan
[107/479] Berhasil: Pabrik Kecerdasan Buatan Eropa
[108/479] Berhasil: PauseAI
[109/479] Berhasil: Pemahaman bahasa alami
[110/479] Berhasil: Pemikiran oportunistik
[111/479] Berhasil: Pengambilalihan oleh kecerdasan buatan
[112/479] Berhasil: Pengenalan tulisan tangan
[113/479] Berhasil: Perantaian balik
[114/479] Berhasil: Perantaian maju
[115/479] Berhasil: Personoid
[116/479] Berhasil: Presenter AI
[117/479] Berhasil: Pusat data AI
[118/479] Berhasil: Pusat Rasionalitas Terapan
[119/479] Berhasil: Radiant AI
[120/479] Berhasil: Recraft
[121/479] Berhasil: Regulasi algoritma
[122/479] Berhasil: Regulasi kecerdasan buatan
[123/479] Berhasil: Representasi dan Penalaran Pengetahuan
[124/479] Berhasil: Riffusion
[125/479] Berhasil: Risiko eksistensial dari kecerdasan buatan
[126/479] Berhasil: Roborace
[127/479] Berhasil: Robot Konstitusi
[128/479] Berhasil: Robot otonom
[129/479] Berhasil: Sastra generatif
[130/479] Berhasil: Siri AI
[131/479] Berhasil: Sistem kendali cerdas
[132/479] Berhasil: Sistem pakar
[133/479] Berhasil: Sistem pelacakan pelamar
[134/479] Berhasil: Slopaganda
[135/479] Berhasil: Society & Organizations Institute
[136/479] Berhasil: Stable Diffusion
[137/479] Berhasil: Supermind AI
[138/479] Berhasil: Unit pemroses tensor
[139/479] Berhasil: Teori Internet Mati
[140/479] Berhasil: Terjemahan mesin
[141/479] Berhasil: The Alignment Problem
[142/479] Berhasil: Théâtre D'opéra Spatial
[143/479] Berhasil: Tingkat simbol
[144/479] Berhasil: Unit pemroses grafis
[145/479] Berhasil: Visi komputer
[146/479] Berhasil: XFA AI
[147/479] Berhasil: Xiaowei
[148/479] Berhasil: Ilmu komputer
[149/479] Berhasil: ACID
[150/479] Berhasil: Algoritma pencarian
[151/479] Berhasil: Aljabar Boole
[152/479] Berhasil: Analis sistem
[153/479] Berhasil: Analisis leksikal
[154/479] Berhasil: Chieko Asakawa
[155/479] Berhasil: Bahasa Dasar Sistem Informasi
[156/479] Berhasil: Bahasa pemrograman domain khusus
[157/479] Berhasil: Blob biner
[158/479] Berhasil: Diagram alir data
[159/479] Berhasil: Engine (ilmu komputer)
[160/479] Berhasil: Epigram dalam pemrograman
[161/479] Berhasil: Filsafat ilmu komputer
[162/479] Berhasil: Hirarki objek
[163/479] Berhasil: Hukum Moore
[164/479] Berhasil: Ilmu data
[165/479] Berhasil: Informatika kedokteran
[166/479] Berhasil: Kernel (ilmu komputer)
[167/479] Berhasil: Kode
[168/479] Berhasil: Kompleksitas Kolmogorov
[169/479] Berhasil: Konkurensi (ilmu komputer)
[170/479] Berhasil: Kontrak pintar
[171/479] Berhasil: Migrasi data
[172/479] Berhasil: NURBS
[173/479] Berhasil: Occam-π
[174/479] Berhasil: Operasi ternary
[175/479] Berhasil: Pemutusan Hubungan Kerja (komputasi)
[176/479] Berhasil: Penambangan data pendidikan
[177/479] Berhasil: Pencarian linear
[178/479] Berhasil: Pencocokan elastisitas
[179/479] Berhasil: Pengisi ruang (ilmu komputer)
[180/479] Berhasil: Penguraian (komputasi)
[181/479] Berhasil: Penyibakan layar
[182/479] Berhasil: Peta memori
[183/479] Berhasil: Pohon urai
[184/479] Berhasil: Pola rancangan
[185/479] Berhasil: Pola serangan
[186/479] Berhasil: Proyeksi (ilmu komputer)
[187/479] Berhasil: PSI Komp 80
[188/479] Berhasil: Psikoinformatika
[189/479] Berhasil: QNX4FS
[190/479] Berhasil: Randy Pausch
[191/479] Berhasil: Rekayasa keandalan situs
[192/479] Berhasil: Sarjana Komputer
[193/479] Berhasil: Semantika (linguistika)
[194/479] Berhasil: Simulasi komputer
[195/479] Berhasil: Sinyal (komunikasi antarproses)
[196/479] Berhasil: Richard Vuduc
[197/479] Berhasil: Pengolahan data
[198/479] Berhasil: Arsitektur Lambda
[199/479] Berhasil: Modus (statistika)
[200/479] Berhasil: Pengolahan data elektronik
[201/479] Berhasil: Pengorekan data
[202/479] Berhasil: Memori non-volatil
[203/479] Berhasil: Memori volatil
[204/479] Berhasil: Nano-RAM
[205/479] Berhasil: Penyimpanan wujud padat
[206/479] Berhasil: Manajemen data
[207/479] Berhasil: Abstraksi (ilmu komputer)
[208/479] Berhasil: Administrator pangkalan data
[209/479] Berhasil: Bahasa kueri
[210/479] Berhasil: Cambridge Analytica
[211/479] Berhasil: Data tertaut
[212/479] Berhasil: Gudang data
[213/479] Berhasil: Hak cipta
[214/479] Berhasil: Injeksi SQL
[215/479] Berhasil: Inteligensi bisnis
[216/479] Berhasil: Kamus data
[217/479] Berhasil: Kolaborasi data
[218/479] Berhasil: Mahadata
[219/479] Berhasil: Manajemen pusat data
[220/479] Berhasil: Normalisasi pangkalan data
[221/479] Berhasil: Open Database Connectivity
[222/479] Berhasil: Pangkalan data berorientasi dokumen
[223/479] Berhasil: Papan pandu (komputasi)
[224/479] Berhasil: Peladen pangkalan data
[225/479] Berhasil: Pemrosesan analitik daring
[226/479] Berhasil: Pemulihan data
[227/479] Berhasil: Penggalian data
[228/479] Berhasil: Penyimpanan data
[229/479] Berhasil: Penyimpanan data kertas
[230/479] Berhasil: Pusat data
[231/479] Berhasil: Rangkap
[232/479] Berhasil: Semafor (pemrograman)
[233/479] Berhasil: Sistem berkas
[234/479] Berhasil: Sistem berkas jaringan
[235/479] Berhasil: Transaksi basis data
[236/479] Berhasil: Verifikasi data
[237/479] Berhasil: Teknologi informasi
[238/479] Berhasil: Akselerasi perangkat keras
[239/479] Berhasil: Arsitektur informasi
[240/479] Berhasil: Attachment Unit Interface
[241/479] Berhasil: Audit teknologi informasi
[242/479] Berhasil: Bayangan data
[243/479] Berhasil: BIOS
[244/479] Berhasil: Boneprice
[245/479] Berhasil: CISA
[246/479] Berhasil: CVE-2022-30190
[247/479] Berhasil: Deep Web
[248/479] Berhasil: Eksabita
[249/479] Berhasil: Eksbibita
[250/479] Berhasil: Ekstranet
[251/479] Berhasil: Enkripsi surel
[252/479] Berhasil: Etika informasi
[253/479] Berhasil: Etika siber
[254/479] Berhasil: Eu-Lisa
[255/479] Berhasil: Evolution-Data Optimized
[256/479] Berhasil: Eyes on the solar system
[257/479] Berhasil: FDDI
[258/479] Berhasil: Format berkas
[259/479] Berhasil: General protection fault
[260/479] Berhasil: Gibibita
[261/479] Berhasil: Goal-based Requirement Analysis Method (GBRAM)
[262/479] Berhasil: Goal-oriented requirements engineering
[263/479] Berhasil: Hak moral
[264/479] Berhasil: Incident Response Planning
[265/479] Berhasil: Informatika sipil
[266/479] Berhasil: Jaringan komputer
[267/479] Berhasil: Kapabilitas Teknologi Informasi
[268/479] Berhasil: Kejahatan komputer
[269/479] Berhasil: Kerangka kerja NFR
[270/479] Berhasil: Kibibita
[271/479] Berhasil: Kolaborasi awan
[272/479] Berhasil: Komunikasi militer
[273/479] Berhasil: Konsorsium Infrastruktur Digital Eropa
[274/479] Berhasil: Konsultansi teknologi informasi
[275/479] Berhasil: Konversi data
[276/479] Berhasil: Kriptografi visual
[277/479] Berhasil: Layanan elektronik
[278/479] Berhasil: Manajemen teknologi bisnis
[279/479] Berhasil: Masyarakat informasi
[280/479] Berhasil: Mebibita
[281/479] Berhasil: Migrasi proses
[282/479] Berhasil: Mode transfer asinkron
[283/479] Berhasil: Pangkalan data daring
[284/479] Berhasil: Pebibita
[285/479] Berhasil: Peladen kolokasi
[286/479] Berhasil: Pemasaran Internet
[287/479] Berhasil: Pemasaran tradisional
[288/479] Berhasil: Penanda sosial
[289/479] Berhasil: Penggalian web
[290/479] Berhasil: Penggunaan terkini
[291/479] Berhasil: Perangkat lunak enkripsi
[292/479] Berhasil: Perdagangan berbasis lokasi
[293/479] Berhasil: Perdagangan elektronik
[294/479] Berhasil: Perdagangan elektronik sosial
[295/479] Berhasil: Perdagangan seluler
[296/479] Berhasil: Perjanjian Teknologi Informasi
[297/479] Berhasil: Permasalahan pada komputasi awan
[298/479] Berhasil: Pertukaran data elektronik
[299/479] Berhasil: Pohon keputusan
[300/479] Berhasil: Pusat Inovasi Digital Eropa
[301/479] Berhasil: Scenario Based Requirement Analysis Method
[302/479] Berhasil: School on Internet Asia
[303/479] Berhasil: SIMES
[304/479] Berhasil: Simple Additive Weighting
[305/479] Berhasil: Sistem e-Pengadaan Pemerintah
[306/479] Berhasil: Sistem informasi pengelolaan
[307/479] Berhasil: Sistem informasi penumpang
[308/479] Berhasil: Stasiun pemancar-penerima dasar
[309/479] Berhasil: Summly
[310/479] Berhasil: Tebibita
[311/479] Berhasil: Teknik komputer dan jaringan
[312/479] Berhasil: Teknologi informasi komunikasi
[313/479] Berhasil: Teknologi informasi komunikasi
[314/479] Berhasil: Teknologi pencari
[315/479] Berhasil: Telepusat
[316/479] Berhasil: TKIP
[317/479] Berhasil: Transformasi digital
[318/479] Berhasil: Tren IT
[319/479] Berhasil: Virtualisasi mejantara
[320/479] Berhasil: WiMAX
[321/479] Berhasil: XDSL
[322/479] Berhasil: Yobibita
[323/479] Berhasil: Yotabita
[324/479] Berhasil: Zebibita
[325/479] Berhasil: Zetabita
[326/479] Berhasil: Demokratisasi teknologi
[327/479] Berhasil: Digitisasi
[328/479] Berhasil: Dompet Identitas Digital Eropa
[329/479] Berhasil: FaceTime
[330/479] Berhasil: Identitas digital
[331/479] Berhasil: Jam digital
[332/479] Berhasil: Keterjangkauan digital
[333/479] Berhasil: Koran digital
[334/479] Berhasil: Scanlation
[335/479] Berhasil: Sekolah Murid Merdeka
[336/479] Berhasil: SMS massal
[337/479] Berhasil: Warga digital
[338/479] Berhasil: Daftar istilah internet
[339/479] Berhasil: .onion
[340/479] Berhasil: 1.1.1.1
[341/479] Berhasil: 11B-X-1371
[342/479] Berhasil: 3.5G
[343/479] Berhasil: 4shared
[344/479] Berhasil: Akses Internet putar-nomor
[345/479] Berhasil: Aktivisme Internet
[346/479] Berhasil: Asymmetric digital subscriber line
[347/479] Berhasil: Bandcamp
[348/479] Berhasil: Banjir informasi
[349/479] Berhasil: Banlists
[350/479] Berhasil: Beberan
[351/479] Berhasil: Biro 1440
[352/479] Berhasil: Bitly
[353/479] Berhasil: Blog
[354/479] Berhasil: Blogroll
[355/479] Berhasil: Budaya internet
[356/479] Berhasil: Cekpremi
[357/479] Berhasil: Centang biru Instagram
[358/479] Berhasil: Citizendium
[359/479] Berhasil: Deezer
[360/479] Berhasil: Demokrasi maya
[361/479] Berhasil: Digibiz
[362/479] Berhasil: DNS over HTTPS
[363/479] Berhasil: DNS over TLS
[364/479] Berhasil: Dunia maya
[365/479] Berhasil: E-PR
[366/479] Berhasil: Eggdrop
[367/479] Berhasil: Free Basics
[368/479] Berhasil: G-Wave
[369/479] Berhasil: Go.com
[370/479] Berhasil: Google Domains
[371/479] Berhasil: Google Public DNS
[372/479] Berhasil: Grup Facebook
[373/479] Berhasil: Hak digital
[374/479] Berhasil: HTTP 410
[375/479] Berhasil: IndosatM2 Broom
[376/479] Berhasil: Internet
[377/479] Berhasil: Internet antarplanet
[378/479] Berhasil: Internet untuk Segala
[379/479] Berhasil: Is Google Making Us Stupid?
[380/479] Berhasil: ISOC
[381/479] Berhasil: Daftar istilah internet Indonesia
[382/479] Berhasil: Jaringan gelap
[383/479] Berhasil: Joox
[384/479] Berhasil: Kata kunci
[385/479] Berhasil: Katalog digital
[386/479] Berhasil: Kawasan bersinyal
[387/479] Berhasil: Keamanan internet
[388/479] Berhasil: Keamanan jaringan
[389/479] Berhasil: Kecanduan internet
[390/479] Berhasil: Kelompok warta
[391/479] Berhasil: Kinerja komputer
[392/479] Berhasil: Komik web
[393/479] Berhasil: Komunitas daring
[394/479] Berhasil: Konvergensi Masyarakat Analog dan Digital di Indonesia
[395/479] Berhasil: Laman
[396/479] Berhasil: Laman web
[397/479] Berhasil: Laporan kebebasan internet
[398/479] Berhasil: Layanan hos web
[399/479] Berhasil: Leonard Kleinrock
[400/479] Berhasil: Literasi web
[401/479] Berhasil: Mail relay
[402/479] Berhasil: Mail transfer agent
[403/479] Berhasil: Milis
[404/479] Berhasil: Manipulasi internet
[405/479] Berhasil: Media daring
[406/479] Berhasil: Meme internet
[407/479] Berhasil: Metanet
[408/479] Berhasil: Milis
[409/479] Berhasil: Mobile Wifi
[410/479] Berhasil: Mobilegeddon
[411/479] Berhasil: MojoPac
[412/479] Berhasil: Nama domain
[413/479] Berhasil: Netralitas net
[414/479] Berhasil: Network Time Protocol
[415/479] Berhasil: Now TV
[416/479] Berhasil: Nyan Cat
[417/479] Berhasil: OpenID
[418/479] Berhasil: Paket aplikasi Internet
[419/479] Berhasil: Pancing sulut
[420/479] Berhasil: Panel Internasional tentang Lingkungan Informasi
[421/479] Berhasil: Parampaa Land
[422/479] Berhasil: Peladen nama rekursif publik
[423/479] Berhasil: Peladen pribadi virtual
[424/479] Berhasil: Pemalsuan alamat IP
[425/479] Berhasil: Pemblokiran
[426/479] Berhasil: Penganalisis paket
[427/479] Berhasil: Pengguna (komputasi)
[428/479] Berhasil: Peramban web
[429/479] Berhasil: Perang peramban web
[430/479] Berhasil: Perangkak web
[431/479] Berhasil: Perangkat lunak sebagai layanan
[432/479] Berhasil: Permainan bermain peran daring multipemain masif
[433/479] Berhasil: Permalink
[434/479] Berhasil: Perpesanan instan
[435/479] Berhasil: Pertanyaan umum
[436/479] Berhasil: Pesan berahi
[437/479] Berhasil: Pidgin (perangkat lunak)
[438/479] Berhasil: Ping (blog)
[439/479] Berhasil: Pita lebar
[440/479] Berhasil: Portal web
[441/479] Berhasil: Pranala
[442/479] Berhasil: PROTECT IP Act
[443/479] Berhasil: Protokol Transpor Waktu Nyata
[444/479] Berhasil: Proyek MPLIK
[445/479] Berhasil: Rekayasa sosial
[446/479] Berhasil: Request for Comments
[447/479] Berhasil: Sejarah Internet
[448/479] Berhasil: Shoutbox
[449/479] Berhasil: Sosiologi internet
[450/479] Berhasil: SoundCloud
[451/479] Berhasil: Spekulasi nama domain
[452/479] Berhasil: Spotify
[453/479] Berhasil: Stop Online Piracy Act
[454/479] Berhasil: Subdomain
[455/479] Berhasil: Subnetwork
[456/479] Berhasil: SweetIM
[457/479] Berhasil: Tantangan Maneken
[458/479] Berhasil: Tarpit (jaringan)
[459/479] Berhasil: Teori kucing lucu
[460/479] Berhasil: The 9
[461/479] Berhasil: The Royal Channel
[462/479] Berhasil: Titik kehadiran
[463/479] Berhasil: Tombol Akses Terbuka
[464/479] Berhasil: Tren Internet
[465/479] Berhasil: Ujaran kebencian
[466/479] Berhasil: United States v. Microsoft Corp.
[467/479] Berhasil: URL palsu
[468/479] Berhasil: Utas percakapan
[469/479] Berhasil: Video campur-gabung
[470/479] Berhasil: Vlog
[471/479] Berhasil: Wajanbolic e-goen
[472/479] Berhasil: WAP site
[473/479] Berhasil: Warung internet
[474/479] Berhasil: Web 3.0
[475/479] Berhasil: Web Hypertext Application Technology Working Group
[476/479] Berhasil: Layanan hos web
[477/479] Berhasil: Webtun
[478/479] Berhasil: Wisaya (perangkat lunak)
[479/479] Berhasil: X.25

Scraping Selesai
Total 479 data artikel berhasil disimpan ke file 'dataset_wikipedia_clean.csv'

## Quality Filtering

In [ ]:
df_result

,Judul,URL,Overview_Isi,Tanggal_Suntingan,Penerbit
0,Algoritma bias,https://id.wikipedia.org/wiki/Algoritma_bias,Algoritma bias menggambarkan galat sistematis ...,1 Juni 2026,Wikipedia Bahasa Indonesia
1,Algoritma Lanczos,https://id.wikipedia.org/wiki/Algoritma_Lanczos,Algoritma Lanczos adalah algoritma iteratif ad...,25 September 2026,Wikipedia Bahasa Indonesia
2,ASCII,https://id.wikipedia.org/wiki/ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia
3,Cermin (komputasi),https://id.wikipedia.org/wiki/Cermin_(komputasi),"Dalam komputasi, sebuah cermin (bahasa Inggris...",27 Mei 2024,Wikipedia Bahasa Indonesia
4,Karakter null,https://id.wikipedia.org/wiki/Karakter_null,"Karakter null (atau bita null), disingkat NUL ...",17 September 2026,Wikipedia Bahasa Indonesia
...,...,...,...,...,...
474,Web Hypertext Application Technology Working G...,https://id.wikipedia.org/wiki/Web_Hypertext_Ap...,Web Hypertext Application Technology Working G...,16 Desember 2022,Wikipedia Bahasa Indonesia
475,Layanan hos web,https://id.wikipedia.org/wiki/Webhosting,Layanan hos web (bahasa Inggris: Web hosting s...,5 September 2025,Wikipedia Bahasa Indonesia
476,Webtun,https://id.wikipedia.org/wiki/Webtun,Webtun (bahasa Korea: 웹툰; bahasa Inggris: webt...,18 September 2026,Wikipedia Bahasa Indonesia
477,Wisaya (perangkat lunak),https://id.wikipedia.org/wiki/Wisaya_(perangka...,Wisaya atau pengatur pasang (bahasa Inggris: w...,18 September 2026,Wikipedia Bahasa Indonesia
478,X.25,https://id.wikipedia.org/wiki/X.25,X.25 adalah sebuah protokol standar ITU-T untu...,18 Oktober 2025,Wikipedia Bahasa Indonesia

In [ ]:
df_result.shape

(479, 5)

In [ ]:
df_result.head()

,Judul,URL,Overview_Isi,Tanggal_Suntingan,Penerbit
0,Algoritma bias,https://id.wikipedia.org/wiki/Algoritma_bias,Algoritma bias menggambarkan galat sistematis ...,1 Juni 2026,Wikipedia Bahasa Indonesia
1,Algoritma Lanczos,https://id.wikipedia.org/wiki/Algoritma_Lanczos,Algoritma Lanczos adalah algoritma iteratif ad...,25 September 2026,Wikipedia Bahasa Indonesia
2,ASCII,https://id.wikipedia.org/wiki/ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia
3,Cermin (komputasi),https://id.wikipedia.org/wiki/Cermin_(komputasi),"Dalam komputasi, sebuah cermin (bahasa Inggris...",27 Mei 2024,Wikipedia Bahasa Indonesia
4,Karakter null,https://id.wikipedia.org/wiki/Karakter_null,"Karakter null (atau bita null), disingkat NUL ...",17 September 2026,Wikipedia Bahasa Indonesia

Lihat duplikasi

In [ ]:
print("jumlah data:", len(df_result))
print("Judul unik:", df_result['Judul'].nunique())
print("URL unik:", df_result['URL'].nunique())

jumlah data: 479
Judul unik: 475
URL unik: 479

Melihat judul yang muncul lebih dari sekali

In [ ]:
duplicate_titles = df_result[
    df_result['Judul'].duplicated(keep=False)
].sort_values('Judul')

duplicate_titles[['Judul', 'URL']]

,Judul,URL
2,ASCII,https://id.wikipedia.org/wiki/ASCII
6,ASCII,https://id.wikipedia.org/wiki/Kode_ASCII
397,Layanan hos web,https://id.wikipedia.org/wiki/Layanan_hos_web
475,Layanan hos web,https://id.wikipedia.org/wiki/Webhosting
402,Milis,https://id.wikipedia.org/wiki/Mailing_list
407,Milis,https://id.wikipedia.org/wiki/Milis
311,Teknologi informasi komunikasi,https://id.wikipedia.org/wiki/Teknologi_Inform...
312,Teknologi informasi komunikasi,https://id.wikipedia.org/wiki/Teknologi_inform...

Melihat distribusi panjang artikel

In [ ]:
df_result['Overview_Isi'].str.len().describe()

count      479.000000
mean      4030.423800
std       4229.138767
min          0.000000
25%       1134.000000
50%       2392.000000
75%       5482.500000
max      24241.000000
Name: Overview_Isi, dtype: float64

Distribusi threshold

In [ ]:
thresholds = [0, 500, 1000, 1500, 2000, 2500, 3000]

for t in thresholds:
    jumlah = (df_result['Overview_Isi'].str.len() >= t).sum()
    print(f"Minimal {t:>4} karakter → {jumlah} artikel")

Minimal    0 karakter → 479 artikel
Minimal  500 karakter → 453 artikel
Minimal 1000 karakter → 374 artikel
Minimal 1500 karakter → 311 artikel
Minimal 2000 karakter → 271 artikel
Minimal 2500 karakter → 232 artikel
Minimal 3000 karakter → 207 artikel

Artikel dengan teks <500 karakter

In [ ]:
df_result['Panjang_Teks'] = df_result['Overview_Isi'].str.len()

df_result[
    df_result['Panjang_Teks'] < 500
][['Judul', 'URL', 'Panjang_Teks']]

,Judul,URL,Panjang_Teks
16,Agen fuzzy,https://id.wikipedia.org/wiki/Agen_fuzzy,378
32,Brainrot Italia,https://id.wikipedia.org/wiki/Brainrot_Italia,0
33,CarynAI,https://id.wikipedia.org/wiki/CarynAI,420
35,Colossus (superkomputer),https://id.wikipedia.org/wiki/Colossus_(superk...,413
45,European High Performance Computing Joint Unde...,https://id.wikipedia.org/wiki/European_High_Pe...,0
60,Inflection AI,https://id.wikipedia.org/wiki/Inflection_AI,410
154,Bahasa Dasar Sistem Informasi,https://id.wikipedia.org/wiki/Bahasa_Dasar_Sis...,231
172,Occam-π,https://id.wikipedia.org/wiki/Occam-%CF%80,413
179,Penguraian (komputasi),https://id.wikipedia.org/wiki/Penguraian_(komp...,382
181,Peta memori,https://id.wikipedia.org/wiki/Peta_memori,426
191,Sarjana Komputer,https://id.wikipedia.org/wiki/Sarjana_Komputer,381
239,Attachment Unit Interface,https://id.wikipedia.org/wiki/Attachment_Unit_...,434
273,Konsultansi teknologi informasi,https://id.wikipedia.org/wiki/Konsultansi_tekn...,470
289,Penggunaan terkini,https://id.wikipedia.org/wiki/Penggunaan_terkini,411
314,Telepusat,https://id.wikipedia.org/wiki/Telepusat,452
337,Daftar istilah internet,https://id.wikipedia.org/wiki/Daftar_istilah_i...,182
348,Banlists,https://id.wikipedia.org/wiki/Banlists,424
352,Blog,https://id.wikipedia.org/wiki/Blog,0
355,Cekpremi,https://id.wikipedia.org/wiki/Cekpremi,422
373,HTTP 410,https://id.wikipedia.org/wiki/HTTP_410,491
375,Internet,https://id.wikipedia.org/wiki/Internet,0
406,Metanet,https://id.wikipedia.org/wiki/Metanet,375
417,Paket aplikasi Internet,https://id.wikipedia.org/wiki/Paket_aplikasi_I...,414
453,Subdomain,https://id.wikipedia.org/wiki/Subdomain,448
459,The 9,https://id.wikipedia.org/wiki/The_9,420
478,X.25,https://id.wikipedia.org/wiki/X.25,296

In [ ]:
articles_list[0]

{'Judul': 'Algoritma bias',
 'URL': 'https://id.wikipedia.org/wiki/Algoritma_bias'}

In [ ]:
articles_list[1]

{'Judul': 'Algoritma Lanczos',
 'URL': 'https://id.wikipedia.org/wiki/Algoritma_Lanczos'}

Kandidat 300 artikel dari hasil threshold >= 1500

In [ ]:
df_candidate = df_result[
    df_result['Panjang_Teks'] >= 1500
].copy()

print("Jumlah kandidat:", len(df_candidate))

Jumlah kandidat: 311

In [ ]:
df_candidate.head()

,Judul,URL,Overview_Isi,Tanggal_Suntingan,Penerbit,Panjang_Teks
0,Algoritma bias,https://id.wikipedia.org/wiki/Algoritma_bias,Algoritma bias menggambarkan galat sistematis ...,1 Juni 2026,Wikipedia Bahasa Indonesia,9968
1,Algoritma Lanczos,https://id.wikipedia.org/wiki/Algoritma_Lanczos,Algoritma Lanczos adalah algoritma iteratif ad...,25 September 2026,Wikipedia Bahasa Indonesia,10448
2,ASCII,https://id.wikipedia.org/wiki/ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia,2153
4,Karakter null,https://id.wikipedia.org/wiki/Karakter_null,"Karakter null (atau bita null), disingkat NUL ...",17 September 2026,Wikipedia Bahasa Indonesia,1762
6,ASCII,https://id.wikipedia.org/wiki/Kode_ASCII,(ASCII) singkatan dari American Standard Code ...,17 September 2026,Wikipedia Bahasa Indonesia,2153

In [ ]:
df_candidate[['Judul', 'Panjang_Teks']].head(20)

                                       Judul  Panjang_Teks
0                             Algoritma bias          9968
1                          Algoritma Lanczos         10448
2                                      ASCII          2153
4                              Karakter null          1762
6                                      ASCII          2153
8                            Komputasi optis          1552
10                   Membangkitkan Kombinasi          1516
11                     Komputasi neuromorfik          1598
12                             Teori otomata          1972
14                         Kecerdasan buatan          7925
17                               Agen otonom          2025
19                                AI Dungeon          6607
20                   AI Love You (film 2022)          2499
21                                 AI winter          4510
23                                  Akinator          1914
24                                Alat Ebert          1728
25                         Algoritma genetik         12713
26                           Algoritma semut          2392
27                   Alice (asisten virtual)         10995
29  Aplikasi kecerdasan buatan untuk militer          3333

Klasifikasi berdasarkan kata pada judul

In [ ]:
import re

def klasifikasi_topik(judul):
    judul = judul.lower()

    # 1. Artificial Intelligence
    if re.search(
        r'ai|kecerdasan buatan|artificial intelligence|'
        r'machine learning|pembelajaran mesin|deep learning|'
        r'jaringan saraf|neural network|computer vision|'
        r'natural language processing|pemrosesan bahasa alami|'
        r'robot|robotika|fuzzy',
        judul
    ):
        return 'AI'

    # 2. Data & Statistics
    elif re.search(
        r'data|basis data|database|statistik|statistika|'
        r'regresi|probabilitas|korelasi|data mining|'
        r'data warehouse|data science|analisis data|'
        r'sistem basis data',
        judul
    ):
        return 'Data & Statistics'

    # 3. Computer Science & Computing
    elif re.search(
        r'algoritma|komputasi|komputer|pemrograman|programming|'
        r'kode|coding|perangkat lunak|software|'
        r'sistem operasi|arsitektur komputer|struktur data|'
        r'compiler|kompilator|bahasa pemrograman|'
        r'kriptografi|jaringan komputer|protokol|'
        r'cpu|prosesor|superkomputer',
        judul
    ):
        return 'Computer Science'

    # 4. Technology, Internet & Digital
    elif re.search(
        r'teknologi|internet|web|digital|informasi|'
        r'cloud|awan|telekomunikasi|jaringan|'
        r'website|situs|media sosial|online|'
        r'http|https|email|server|hosting',
        judul
    ):
        return 'Technology & Internet'

    else:
        return 'Other'

In [ ]:
df_candidate['Topik_Sementara'] = df_candidate['Judul'].apply(
    klasifikasi_topik
)

In [ ]:
df_candidate.columns

Index(['Judul', 'URL', 'Overview_Isi', 'Tanggal_Suntingan', 'Penerbit',
       'Panjang_Teks', 'Topik_Sementara'],
      dtype='object')

In [ ]:
df_candidate['Topik_Sementara'].value_counts()

Topik_Sementara
Other                    164
Technology & Internet     52
AI                        47
Computer Science          25
Data & Statistics         23
Name: count, dtype: int64

In [ ]:
df_candidate[
    df_candidate['Topik_Sementara'] == 'Other'
][['Judul', 'Panjang_Teks']]

                                Judul  Panjang_Teks
2                               ASCII          2153
4                       Karakter null          1762
6                               ASCII          2153
10            Membangkitkan Kombinasi          1516
12                      Teori otomata          1972
..                                ...           ...
462              Tombol Akses Terbuka          3268
464                  Ujaran kebencian          3501
465  United States v. Microsoft Corp.          3311
469                              Vlog         12275
471                          WAP site          3910

[164 rows x 2 columns]

Interprestasi : Ternyata masih ada duplikat dan jumlah pemilihan topik belum seimbang

In [ ]:
df_candidate = df_candidate.drop_duplicates(
    subset=['Judul'],
    keep='first'
).copy()

print("Jumlah setelah menghapus judul duplikat:", len(df_candidate))

Jumlah setelah menghapus judul duplikat: 307

In [ ]:
df_candidate[['Judul', 'URL']].head(20)

,Judul,URL
0,Algoritma bias,https://id.wikipedia.org/wiki/Algoritma_bias
1,Algoritma Lanczos,https://id.wikipedia.org/wiki/Algoritma_Lanczos
2,ASCII,https://id.wikipedia.org/wiki/ASCII
4,Karakter null,https://id.wikipedia.org/wiki/Karakter_null
8,Komputasi optis,https://id.wikipedia.org/wiki/Komputasi_optis
10,Membangkitkan Kombinasi,https://id.wikipedia.org/wiki/Membangkitkan_Ko...
11,Komputasi neuromorfik,https://id.wikipedia.org/wiki/Komputasi_neurom...
12,Teori otomata,https://id.wikipedia.org/wiki/Teori_otomata
14,Kecerdasan buatan,https://id.wikipedia.org/wiki/Kecerdasan_buatan
17,Agen otonom,https://id.wikipedia.org/wiki/Agen_otonom
19,AI Dungeon,https://id.wikipedia.org/wiki/AI_Dungeon
20,AI Love You (film 2022),https://id.wikipedia.org/wiki/AI_Love_You_(fil...
21,AI winter,https://id.wikipedia.org/wiki/AI_winter
23,Akinator,https://id.wikipedia.org/wiki/Akinator
24,Alat Ebert,https://id.wikipedia.org/wiki/Alat_Ebert
25,Algoritma genetik,https://id.wikipedia.org/wiki/Algoritma_genetik
26,Algoritma semut,https://id.wikipedia.org/wiki/Algoritma_semut
27,Alice (asisten virtual),https://id.wikipedia.org/wiki/Alice_(asisten_v...
29,Aplikasi kecerdasan buatan untuk militer,https://id.wikipedia.org/wiki/Aplikasi_kecerda...
30,Apple Intelligence,https://id.wikipedia.org/wiki/Apple_Intelligence

Buat clasifier baru

In [ ]:
import re

def klasifikasi_topik(judul):
    judul = judul.lower().strip()


    # 1. ARTIFICIAL INTELLIGENCE
    if re.search(
        r'\b(ai|kecerdasan buatan|artificial intelligence|'
        r'machine learning|pembelajaran mesin|deep learning|'
        r'jaringan saraf|neural network|computer vision|'
        r'natural language processing|pemrosesan bahasa alami|'
        r'nlp|robotika|robot|fuzzy|sistem pakar)\b',
        judul
    ):
        return 'AI'

    # 2. DATA & STATISTICS
    elif re.search(
        r'\b(data science|ilmu data|data mining|'
        r'data warehouse|big data|database|basis data|'
        r'pengolahan data|analisis data|'
        r'statistik|statistika|regresi|probabilitas|'
        r'korelasi|distribusi statistik)\b',
        judul
    ):
        return 'Data & Statistics'

    # 3. COMPUTER SCIENCE
    elif re.search(
        r'\b(algoritma|komputasi|komputer|'
        r'pemrograman|programming|program|'
        r'perangkat lunak|software|'
        r'struktur data|otomata|automata|'
        r'teori komputasi|bahasa pemrograman|'
        r'compiler|kompilator|'
        r'sistem operasi|arsitektur komputer|'
        r'prosesor|processor|cpu|gpu|'
        r'memori komputer|kriptografi|'
        r'karakter null|ascii|bit|byte|'
        r'kode komputer|sistem komputer)\b',
        judul
    ):
        return 'Computer Science'

    # 4. TECHNOLOGY & INTERNET
    elif re.search(
        r'\b(teknologi informasi|teknologi digital|'
        r'teknologi|internet|internet|web|website|'
        r'world wide web|www|browser|'
        r'cloud|komputasi awan|server|hosting|'
        r'http|https|email|'
        r'telekomunikasi|aplikasi|'
        r'smartphone|ponsel|media sosial|'
        r'digital|jaringan komputer|'
        r'jaringan internet|wap)\b',
        judul
    ):
        return 'Technology & Internet'

    else:
        return 'Other'

In [ ]:
df_candidate['Topik_Sementara'] = df_candidate['Judul'].apply(
    klasifikasi_topik
)

In [ ]:
df_candidate['Topik_Sementara'].value_counts()

Topik_Sementara
Other                    196
AI                        39
Technology & Internet     38
Computer Science          28
Data & Statistics          6
Name: count, dtype: int64

In [ ]:
other_titles = df_candidate[
    df_candidate['Topik_Sementara'] == 'Other'
]['Judul'].tolist()

for i, judul in enumerate(other_titles, 1):
    print(f"{i}. {judul}")

1. Membangkitkan Kombinasi
2. Agen otonom
3. Akinator
4. Alat Ebert
5. Alice (asisten virtual)
6. Apple Intelligence
7. Asisten Google
8. Claude (model bahasa)
9. Cruel World of Dreams and Fears
10. Destination Earth
11. Empati buatan
12. EU-SysFlex
13. Future of Life Institute
14. Google Klip
15. H (perusahaan)
16. Hak atas realitas
17. Imagen (model teks-ke-gambar)
18. Inisiatif Pencitraan Kanker Eropa
19. Institut Penelitian Kecerdasan Mesin
20. Kebijaksanaan buatan
21. Kebodohan buatan
22. Kedekatan buatan
23. Kematian Elaine Herzberg
24. Keruntuhan model
25. Kesadaran buatan
26. Komunitas rasionalis
27. Krisis pasokan memori global 2025-sekarang
28. Kórsafn
29. Masyarakat 5.0
30. Mata v. Avianca, Inc.
31. Midjourney
32. Model teks-ke-gambar
33. Muse Spark
34. OpenAI
35. Otak buatan
36. PauseAI
37. Pemahaman bahasa alami
38. Pengenalan tulisan tangan
39. Pusat Rasionalitas Terapan
40. Recraft
41. Representasi dan Penalaran Pengetahuan
42. Riffusion
43. Roborace
44. Sastra generatif
45. Sistem kendali cerdas
46. Sistem pelacakan pelamar
47. Slopaganda
48. Stable Diffusion
49. Unit pemroses tensor
50. Terjemahan mesin
51. The Alignment Problem
52. Théâtre D'opéra Spatial
53. Unit pemroses grafis
54. ACID
55. Aljabar Boole
56. Analis sistem
57. Analisis leksikal
58. Chieko Asakawa
59. Diagram alir data
60. Hukum Moore
61. Informatika kedokteran
62. Kode
63. Kontrak pintar
64. NURBS
65. Operasi ternary
66. Penambangan data pendidikan
67. Penyibakan layar
68. Pohon urai
69. Pola rancangan
70. Pola serangan
71. PSI Komp 80
72. Psikoinformatika
73. Randy Pausch
74. Semantika (linguistika)
75. Arsitektur Lambda
76. Memori volatil
77. Nano-RAM
78. Manajemen data
79. Cambridge Analytica
80. Data tertaut
81. Hak cipta
82. Injeksi SQL
83. Inteligensi bisnis
84. Kolaborasi data
85. Mahadata
86. Manajemen pusat data
87. Normalisasi pangkalan data
88. Pangkalan data berorientasi dokumen
89. Pemrosesan analitik daring
90. Pemulihan data
91. Penggalian data
92. Penyimpanan data kertas
93. Pusat data
94. Rangkap
95. Sistem berkas jaringan
96. Akselerasi perangkat keras
97. Arsitektur informasi
98. Bayangan data
99. BIOS
100. Boneprice
101. Enkripsi surel
102. Etika informasi
103. Etika siber
104. Eu-Lisa
105. Evolution-Data Optimized
106. Eyes on the solar system
107. General protection fault
108. Goal-based Requirement Analysis Method (GBRAM)
109. Goal-oriented requirements engineering
110. Hak moral
111. Informatika sipil
112. Kerangka kerja NFR
113. Kibibita
114. Kolaborasi awan
115. Komunikasi militer
116. Konversi data
117. Layanan elektronik
118. Masyarakat informasi
119. Mode transfer asinkron
120. Pemasaran tradisional
121. Penanda sosial
122. Perdagangan elektronik
123. Perdagangan elektronik sosial
124. Perdagangan seluler
125. Pertukaran data elektronik
126. Pohon keputusan
127. Scenario Based Requirement Analysis Method
128. Sistem e-Pengadaan Pemerintah
129. Sistem informasi pengelolaan
130. Sistem informasi penumpang
131. Stasiun pemancar-penerima dasar
132. Summly
133. Tren IT
134. Virtualisasi mejantara
135. WiMAX
136. XDSL
137. Digitisasi
138. FaceTime
139. Scanlation
140. Sekolah Murid Merdeka
141. 1.1.1.1
142. 11B-X-1371
143. 3.5G
144. 4shared
145. Bandcamp
146. Banjir informasi
147. Biro 1440
148. Bitly
149. Citizendium
150. Deezer
151. Demokrasi maya
152. Digibiz
153. Dunia maya
154. E-PR
155. Go.com
156. IndosatM2 Broom
157. Is Google Making Us Stupid?
158. Jaringan gelap
159. Kata kunci
160. Kawasan bersinyal
161. Keamanan jaringan
162. Laman
163. Leonard Kleinrock
164. Mail relay
165. Milis
166. Media daring
167. MojoPac
168. Netralitas net
169. Network Time Protocol
170. Now TV
171. OpenID
172. Pancing sulut
173. Panel Internasional tentang Lingkungan Informasi
174. Pemalsuan alamat IP
175. Pemblokiran
176. Permainan bermain peran daring multipemain masif
177. Perpesanan instan
178. Pesan berahi
179. Pita lebar
180. Pranala
181. PROTECT IP Act
182. Protokol Transpor Waktu Nyata
183. Rekayasa sosial
184. Spekulasi nama domain
185. Spotify
186. Stop Online Piracy Act
187. SweetIM
188. Tantangan Maneken
189. Tarpit (jaringan)
190. Teori kucing lucu
191. The Royal Channel
192. Titik kehadiran
193. Tombol Akses Terbuka
194. Ujaran kebencian
195. United States v. Microsoft Corp.
196. Vlog

Melihat seluruh judul artikel dari 296 kandidat artikel (tanpa duplikat)

In [ ]:
for i, judul in enumerate(df_candidate['Judul'].tolist()[:100], 1):
    print(f"{i}. {judul}")

1. Algoritma bias
2. Algoritma Lanczos
3. ASCII
4. Karakter null
5. Komputasi optis
6. Membangkitkan Kombinasi
7. Komputasi neuromorfik
8. Teori otomata
9. Kecerdasan buatan
10. Agen otonom
11. AI Dungeon
12. AI Love You (film 2022)
13. AI winter
14. Akinator
15. Alat Ebert
16. Algoritma genetik
17. Algoritma semut
18. Alice (asisten virtual)
19. Aplikasi kecerdasan buatan untuk militer
20. Apple Intelligence
21. Asisten Google
22. Claude (model bahasa)
23. Cruel World of Dreams and Fears
24. Dampak lingkungan dari kecerdasan buatan
25. Deep Learning (South Park)
26. Destination Earth
27. Diella (sistem AI)
28. Efek kecerdasan buatan
29. Empati buatan
30. Etika dalam kecerdasan buatan
31. EU-SysFlex
32. Figure AI
33. Future of Life Institute
34. Galaxy AI
35. GOLOG (bahasa pemrograman)
36. Google AI Studio
37. Google Klip
38. H (perusahaan)
39. Hak atas realitas
40. Halusinasi (kecerdasan buatan)
41. Imagen (model teks-ke-gambar)
42. Inisiatif Pencitraan Kanker Eropa
43. Institut Penelitian Kecerdasan Mesin
44. Jaringan Saraf (perangkat lunak)
45. Jaringan saraf tiruan
46. Kantor Kecerdasan Buatan Eropa
47. Keamanan kecerdasan buatan
48. Kebijaksanaan buatan
49. Kebodohan buatan
50. Penerapan kecerdasan buatan
51. Kecerdasan buatan dalam fiksi
52. Kecerdasan buatan dalam kesehatan mental
53. Kecerdasan buatan dalam proyek-proyek Wikimedia
54. Kecerdasan buatan dan hak cipta
55. Kecerdasan buatan generatif
56. Kecerdasan buatan simbolik
57. Kedekatan buatan
58. Kematian Elaine Herzberg
59. Keruntuhan model
60. Kesadaran buatan
61. Kling AI (perusahaan)
62. Komunitas rasionalis
63. Kongres Keamanan Kecerdasan Buatan
64. Kontroversi kecerdasan buatan
65. Krisis pasokan memori global 2025-sekarang
66. Kórsafn
67. Masalah pengendalian kecerdasan buatan
68. Masyarakat 5.0
69. Mata v. Avianca, Inc.
70. Midjourney
71. Model teks-ke-gambar
72. Muse Spark
73. OpenAI
74. Otak buatan
75. Pabrik Kecerdasan Buatan Eropa
76. PauseAI
77. Pemahaman bahasa alami
78. Pengambilalihan oleh kecerdasan buatan
79. Pengenalan tulisan tangan
80. Presenter AI
81. Pusat data AI
82. Pusat Rasionalitas Terapan
83. Radiant AI
84. Recraft
85. Regulasi algoritma
86. Regulasi kecerdasan buatan
87. Representasi dan Penalaran Pengetahuan
88. Riffusion
89. Risiko eksistensial dari kecerdasan buatan
90. Roborace
91. Robot otonom
92. Sastra generatif
93. Siri AI
94. Sistem kendali cerdas
95. Sistem pakar
96. Sistem pelacakan pelamar
97. Slopaganda
98. Stable Diffusion
99. Unit pemroses tensor
100. Teori Internet Mati

In [ ]:
for i, judul in enumerate(df_candidate['Judul'].tolist()[100:200], 101):
    print(f"{i}. {judul}")

101. Terjemahan mesin
102. The Alignment Problem
103. Théâtre D'opéra Spatial
104. Unit pemroses grafis
105. Visi komputer
106. Ilmu komputer
107. ACID
108. Algoritma pencarian
109. Aljabar Boole
110. Analis sistem
111. Analisis leksikal
112. Chieko Asakawa
113. Bahasa pemrograman domain khusus
114. Diagram alir data
115. Hukum Moore
116. Ilmu data
117. Informatika kedokteran
118. Kernel (ilmu komputer)
119. Kode
120. Kontrak pintar
121. NURBS
122. Operasi ternary
123. Penambangan data pendidikan
124. Penyibakan layar
125. Pohon urai
126. Pola rancangan
127. Pola serangan
128. PSI Komp 80
129. Psikoinformatika
130. Randy Pausch
131. Semantika (linguistika)
132. Simulasi komputer
133. Pengolahan data
134. Arsitektur Lambda
135. Modus (statistika)
136. Pengolahan data elektronik
137. Memori volatil
138. Nano-RAM
139. Manajemen data
140. Abstraksi (ilmu komputer)
141. Cambridge Analytica
142. Data tertaut
143. Hak cipta
144. Injeksi SQL
145. Inteligensi bisnis
146. Kolaborasi data
147. Mahadata
148. Manajemen pusat data
149. Normalisasi pangkalan data
150. Open Database Connectivity
151. Pangkalan data berorientasi dokumen
152. Pemrosesan analitik daring
153. Pemulihan data
154. Penggalian data
155. Penyimpanan data kertas
156. Pusat data
157. Rangkap
158. Semafor (pemrograman)
159. Sistem berkas jaringan
160. Transaksi basis data
161. Teknologi informasi
162. Akselerasi perangkat keras
163. Arsitektur informasi
164. Bayangan data
165. BIOS
166. Boneprice
167. Deep Web
168. Enkripsi surel
169. Etika informasi
170. Etika siber
171. Eu-Lisa
172. Evolution-Data Optimized
173. Eyes on the solar system
174. General protection fault
175. Goal-based Requirement Analysis Method (GBRAM)
176. Goal-oriented requirements engineering
177. Hak moral
178. Informatika sipil
179. Jaringan komputer
180. Kerangka kerja NFR
181. Kibibita
182. Kolaborasi awan
183. Komunikasi militer
184. Konsorsium Infrastruktur Digital Eropa
185. Konversi data
186. Kriptografi visual
187. Layanan elektronik
188. Masyarakat informasi
189. Mode transfer asinkron
190. Pemasaran Internet
191. Pemasaran tradisional
192. Penanda sosial
193. Penggalian web
194. Perangkat lunak enkripsi
195. Perdagangan elektronik
196. Perdagangan elektronik sosial
197. Perdagangan seluler
198. Permasalahan pada komputasi awan
199. Pertukaran data elektronik
200. Pohon keputusan

In [ ]:
for i, judul in enumerate(df_candidate['Judul'].tolist()[200:], 201):
    print(f"{i}. {judul}")

201. Pusat Inovasi Digital Eropa
202. Scenario Based Requirement Analysis Method
203. School on Internet Asia
204. Sistem e-Pengadaan Pemerintah
205. Sistem informasi pengelolaan
206. Sistem informasi penumpang
207. Stasiun pemancar-penerima dasar
208. Summly
209. Teknologi informasi komunikasi
210. Teknologi pencari
211. Transformasi digital
212. Tren IT
213. Virtualisasi mejantara
214. WiMAX
215. XDSL
216. Digitisasi
217. Dompet Identitas Digital Eropa
218. FaceTime
219. Identitas digital
220. Keterjangkauan digital
221. Scanlation
222. Sekolah Murid Merdeka
223. Warga digital
224. 1.1.1.1
225. 11B-X-1371
226. 3.5G
227. 4shared
228. Aktivisme Internet
229. Asymmetric digital subscriber line
230. Bandcamp
231. Banjir informasi
232. Biro 1440
233. Bitly
234. Budaya internet
235. Citizendium
236. Deezer
237. Demokrasi maya
238. Digibiz
239. Dunia maya
240. E-PR
241. Go.com
242. Hak digital
243. IndosatM2 Broom
244. Internet untuk Segala
245. Is Google Making Us Stupid?
246. Daftar istilah internet Indonesia
247. Jaringan gelap
248. Kata kunci
249. Katalog digital
250. Kawasan bersinyal
251. Keamanan internet
252. Keamanan jaringan
253. Kecanduan internet
254. Kinerja komputer
255. Konvergensi Masyarakat Analog dan Digital di Indonesia
256. Laman
257. Laman web
258. Laporan kebebasan internet
259. Layanan hos web
260. Leonard Kleinrock
261. Mail relay
262. Milis
263. Manipulasi internet
264. Media daring
265. Meme internet
266. MojoPac
267. Netralitas net
268. Network Time Protocol
269. Now TV
270. OpenID
271. Pancing sulut
272. Panel Internasional tentang Lingkungan Informasi
273. Pemalsuan alamat IP
274. Pemblokiran
275. Pengguna (komputasi)
276. Peramban web
277. Perangkat lunak sebagai layanan
278. Permainan bermain peran daring multipemain masif
279. Perpesanan instan
280. Pesan berahi
281. Pidgin (perangkat lunak)
282. Pita lebar
283. Portal web
284. Pranala
285. PROTECT IP Act
286. Protokol Transpor Waktu Nyata
287. Rekayasa sosial
288. Sejarah Internet
289. Sosiologi internet
290. Spekulasi nama domain
291. Spotify
292. Stop Online Piracy Act
293. SweetIM
294. Tantangan Maneken
295. Tarpit (jaringan)
296. Teori kucing lucu
297. The Royal Channel
298. Titik kehadiran
299. Tombol Akses Terbuka
300. Tren Internet
301. Ujaran kebencian
302. United States v. Microsoft Corp.
303. Vlog
304. WAP site
305. Warung internet
306. Web 3.0
307. Wisaya (perangkat lunak)

Buat daftar 25 artikel AI

In [ ]:
ai = [
    "Kecerdasan buatan",
    "Agen otonom",
    "Algoritma genetik",
    "Algoritma semut",
    "Apple Intelligence",
    "Claude (model bahasa)",
    "Dampak lingkungan dari kecerdasan buatan",
    "Etika dalam kecerdasan buatan",
    "Halusinasi (kecerdasan buatan)",
    "Jaringan saraf tiruan",
    "Keamanan kecerdasan buatan",
    "Penerapan kecerdasan buatan",
    "Kecerdasan buatan generatif",
    "Kecerdasan buatan simbolik",
    "Keruntuhan model",
    "Kesadaran buatan",
    "Masalah pengendalian kecerdasan buatan",
    "Midjourney",
    "Model teks-ke-gambar",
    "OpenAI",
    "Pemahaman bahasa alami",
    "Pengenalan tulisan tangan",
    "Representasi dan Penalaran Pengetahuan",
    "Stable Diffusion",
    "Visi komputer"
]

print("Jumlah AI:", len(ai))

Jumlah AI: 25

Buat daftar 30 Computer Science

In [ ]:
computer_science = [
    "Algoritma bias",
    "Algoritma Lanczos",
    "ASCII",
    "Karakter null",
    "Komputasi optis",
    "Membangkitkan Kombinasi",
    "Komputasi neuromorfik",
    "Teori otomata",
    "Ilmu komputer",
    "Algoritma pencarian",
    "Aljabar Boole",
    "Analisis leksikal",
    "Bahasa pemrograman domain khusus",
    "Kernel (ilmu komputer)",
    "Kode",
    "Operasi ternary",
    "Pohon urai",
    "Pola rancangan",
    "Simulasi komputer",
    "Abstraksi (ilmu komputer)",
    "GOLOG (bahasa pemrograman)",
    "Semafor (pemrograman)",
    "General protection fault",
    "BIOS",
    "Hukum Moore",
    "Unit pemroses grafis",
    "Sistem pakar",
    "NURBS",
    "Pola serangan",
    "Akselerasi perangkat keras"
]

print("Jumlah Computer Science:", len(computer_science))

Jumlah Computer Science: 30

Buat daftar 20 Data & Statistic

In [ ]:
data_statistics = [
    "Ilmu data",
    "Diagram alir data",
    "Penambangan data pendidikan",
    "Pengolahan data",
    "Modus (statistika)",
    "Pengolahan data elektronik",
    "Manajemen data",
    "Data tertaut",
    "Injeksi SQL",
    "Inteligensi bisnis",
    "Kolaborasi data",
    "Mahadata",
    "Manajemen pusat data",
    "Normalisasi pangkalan data",
    "Open Database Connectivity",
    "Pangkalan data berorientasi dokumen",
    "Pemrosesan analitik daring",
    "Pemulihan data",
    "Penggalian data",
    "Transaksi basis data"
]

print("Jumlah Data & Statistics:", len(data_statistics))

Jumlah Data & Statistics: 20

Buat daftar 25 Technology & Internet

In [ ]:
technology_internet = [
    "Teknologi informasi",
    "Arsitektur informasi",
    "Deep Web",
    "Enkripsi surel",
    "Etika informasi",
    "Etika siber",
    "Jaringan komputer",
    "Kolaborasi awan",
    "Konversi data",
    "Layanan elektronik",
    "Mode transfer asinkron",
    "Pemasaran Internet",
    "Penggalian web",
    "Perangkat lunak enkripsi",
    "Perdagangan elektronik",
    "Permasalahan pada komputasi awan",
    "Pertukaran data elektronik",
    "Teknologi informasi komunikasi",
    "Transformasi digital",
    "WiMAX",
    "XDSL",
    "Asymmetric digital subscriber line",
    "Internet untuk Segala",
    "Keamanan jaringan",
    "Peramban web"
]

print("Jumlah Technology & Internet:", len(technology_internet))

Jumlah Technology & Internet: 25

In [ ]:
judul_final = ai + computer_science + data_statistics + technology_internet
df_final = df_candidate[
    df_candidate["Judul"].isin(judul_final)
].copy()

In [ ]:
print("Jumlah artikel final:", len(df_final))

Jumlah artikel final: 100

Pastikan tidak ada judul yang hilang

In [ ]:
judul_tidak_ditemukan = set(judul_final) - set(df_final["Judul"])

print("Jumlah judul yang tidak ditemukan:", len(judul_tidak_ditemukan))

for judul in sorted(judul_tidak_ditemukan):
    print("-", judul)

Jumlah judul yang tidak ditemukan: 0

Tambahkan kategori final

In [ ]:
kategori_final = {}

for judul in ai:
    kategori_final[judul] = "AI"

for judul in computer_science:
    kategori_final[judul] = "Computer Science"

for judul in data_statistics:
    kategori_final[judul] = "Data & Statistics"

for judul in technology_internet:
    kategori_final[judul] = "Technology & Internet"

In [ ]:
df_final["Topik"] = df_final["Judul"].map(kategori_final)

print("Jumlah artikel:", len(df_final))
print("Judul unik:", df_final["Judul"].nunique())
print("URL unik:", df_final["URL"].nunique())
print()
print(df_final["Topik"].value_counts())

Jumlah artikel: 100
Judul unik: 100
URL unik: 100

Topik
Computer Science         30
AI                       25
Technology & Internet    25
Data & Statistics        20
Name: count, dtype: int64

### Extracting hasil scraping HTTP to .csv

In [111]:
df_final_export = df_final[['Judul', 'Overview_Isi', 'URL']].copy()

df_final_export['topik'] = df_final_export['Judul'].map(kategori_final)

df_final_export.columns = ['judul', 'teks', 'url', 'topik']

df_final_export.insert(0, 'no', range(1, len(df_final_export) + 1))

df_final_export.to_csv('hasil_scraping_http.csv', index=False)

print("Berhasil menyimpan df_final dengan kolom topik ke 'hasil_scraping_http.csv'!")
print(df_final_export.head())

Berhasil menyimpan df_final dengan kolom topik ke 'hasil_scraping_http.csv'!
   no              judul                                               teks  \
0   1     Algoritma bias  Algoritma bias menggambarkan galat sistematis ...
1   2  Algoritma Lanczos  Algoritma Lanczos adalah algoritma iteratif ad...
2   3              ASCII  (ASCII) singkatan dari American Standard Code ...
4   4      Karakter null  Karakter null (atau bita null), disingkat NUL ...
8   5    Komputasi optis  Komputasi optis adalah penggunaan foton yang d...

                                               url             topik
0     https://id.wikipedia.org/wiki/Algoritma_bias  Computer Science
1  https://id.wikipedia.org/wiki/Algoritma_Lanczos  Computer Science
2              https://id.wikipedia.org/wiki/ASCII  Computer Science
4      https://id.wikipedia.org/wiki/Karakter_null  Computer Science
8    https://id.wikipedia.org/wiki/Komputasi_optis  Computer Science

## API

In [ ]:
import requests
import time
import pandas as pd

api_url = "https://id.wikipedia.org/w/api.php"

headers = {
    "User-Agent": "PemrosesanTeks-UNESA/1.0 (student course project)"
}

Fungsi untuk mengambil satu artikel Wikipedia melalui MediaWiki API dengan mekanisme retry dan penanganan rate limit

In [ ]:


def get_wikipedia_api_safe(judul, max_retries=5):

    params = {
        "action": "query",
        "prop": "extracts",
        "explaintext": True,
        "exsectionformat": "plain",
        "titles": judul,
        "format": "json"
    }

    for attempt in range(max_retries):

        response = requests.get(
            api_url,
            params=params,
            headers=headers,
            timeout=60
        )

        # Berhasil
        if response.status_code == 200:

            data = response.json()
            pages = data["query"]["pages"]

            page = next(iter(pages.values()))

            return {
                "Judul": page.get("title", judul),
                "API_Text": page.get("extract", "")
            }

        # Terkena rate limit
        elif response.status_code == 429:

            retry_after = response.headers.get("Retry-After")

            if retry_after:
                wait_time = int(retry_after)
            else:
                wait_time = 5 * (attempt + 1)

            print(
                f"429 untuk '{judul}'. "
                f"Menunggu {wait_time} detik..."
            )

            time.sleep(wait_time)

        # Error lainnya
        else:

            print(
                f"Error {response.status_code} "
                f"untuk '{judul}'"
            )

            time.sleep(5)

    return {
        "Judul": judul,
        "API_Text": ""
    }

Uji coba API pada 5 artikel

In [ ]:
test_single = get_wikipedia_api_safe("Algoritma Lanczos")

print("Judul:", test_single["Judul"])
print("Panjang:", len(test_single["API_Text"]))
print()
print(test_single["API_Text"][:500])

Judul: Algoritma Lanczos
Panjang: 24279

Algoritma Lanczos adalah algoritma iteratif adaptasi dari metode daya (power method) untuk menemukan



        m


    {\displaystyle m}

 nilai dan vektor eigen yang "paling berguna" (umumnya yang tertinggi/terendah) dari sebuah matriks Hermite berukuran



        n
        ×
        n


    {\displaystyle n\times n}

, dengan



        m


    {\displaystyle m}

 tidak perlu jauh lebih kecil dari

In [ ]:
test_titles = df_final["Judul"].head(5).tolist()

test_results = []

for judul in test_titles:

    print(f"Mengambil: {judul}")

    hasil = get_wikipedia_api_safe(judul)
    test_results.append(hasil)

    print(f"Panjang teks: {len(hasil['API_Text'])}")

    # jeda antar request
    time.sleep(2)

Mengambil: Algoritma bias
Panjang teks: 9922
Mengambil: Algoritma Lanczos
Panjang teks: 24279
Mengambil: ASCII
Panjang teks: 2381
Mengambil: Karakter null
Panjang teks: 1768
Mengambil: Komputasi optis
Panjang teks: 1598

In [ ]:
df_api_test = pd.DataFrame(test_results)

print(df_api_test[["Judul", "API_Text"]])

print(
    "Jumlah artikel:",
    len(df_api_test)
)

print(
    "Teks kosong:",
    (df_api_test["API_Text"].str.len() == 0).sum()
)

               Judul                                           API_Text
0     Algoritma bias  Algoritma bias menggambarkan galat sistematis ...
1  Algoritma Lanczos  Algoritma Lanczos adalah algoritma iteratif ad...
2              ASCII  (ASCII) singkatan dari American Standard Code ...
3      Karakter null  Karakter null (atau bita null), disingkat NUL ...
4    Komputasi optis  Komputasi optis adalah penggunaan foton yang d...
Jumlah artikel: 5
Teks kosong: 0

Ambil 100 Artikel dari df_final

In [ ]:
api_articles = []

for i, judul in enumerate(df_final["Judul"], start=1):

    print(f"[{i}/100] Mengambil: {judul}")

    hasil = get_wikipedia_api_safe(judul)
    api_articles.append(hasil)

    print(f"    Panjang teks: {len(hasil['API_Text'])}")

    # jeda agar tidak terlalu cepat
    time.sleep(2)

[1/100] Mengambil: Algoritma bias
    Panjang teks: 9922
[2/100] Mengambil: Algoritma Lanczos
    Panjang teks: 24279
[3/100] Mengambil: ASCII
    Panjang teks: 2381
[4/100] Mengambil: Karakter null
    Panjang teks: 1768
[5/100] Mengambil: Komputasi optis
    Panjang teks: 1598
[6/100] Mengambil: Membangkitkan Kombinasi
429 untuk 'Membangkitkan Kombinasi'. Menunggu 29 detik...
    Panjang teks: 3260
[7/100] Mengambil: Komputasi neuromorfik
    Panjang teks: 2464
[8/100] Mengambil: Teori otomata
    Panjang teks: 6619
[9/100] Mengambil: Kecerdasan buatan
    Panjang teks: 11028
[10/100] Mengambil: Agen otonom
    Panjang teks: 2375
[11/100] Mengambil: Algoritma genetik
    Panjang teks: 13458
[12/100] Mengambil: Algoritma semut
    Panjang teks: 2308
[13/100] Mengambil: Apple Intelligence
    Panjang teks: 4022
[14/100] Mengambil: Claude (model bahasa)
    Panjang teks: 5646
[15/100] Mengambil: Dampak lingkungan dari kecerdasan buatan
    Panjang teks: 8203
[16/100] Mengambil: Etika dalam kecerdasan buatan
429 untuk 'Etika dalam kecerdasan buatan'. Menunggu 36 detik...
    Panjang teks: 12260
[17/100] Mengambil: GOLOG (bahasa pemrograman)
    Panjang teks: 6961
[18/100] Mengambil: Halusinasi (kecerdasan buatan)
    Panjang teks: 7909
[19/100] Mengambil: Jaringan saraf tiruan
    Panjang teks: 16724
[20/100] Mengambil: Keamanan kecerdasan buatan
    Panjang teks: 6224
[21/100] Mengambil: Penerapan kecerdasan buatan
    Panjang teks: 5421
[22/100] Mengambil: Kecerdasan buatan generatif
    Panjang teks: 13509
[23/100] Mengambil: Kecerdasan buatan simbolik
    Panjang teks: 4562
[24/100] Mengambil: Keruntuhan model
    Panjang teks: 4629
[25/100] Mengambil: Kesadaran buatan
    Panjang teks: 5620
[26/100] Mengambil: Masalah pengendalian kecerdasan buatan
429 untuk 'Masalah pengendalian kecerdasan buatan'. Menunggu 36 detik...
    Panjang teks: 2687
[27/100] Mengambil: Midjourney
    Panjang teks: 5770
[28/100] Mengambil: Model teks-ke-gambar
    Panjang teks: 5313
[29/100] Mengambil: OpenAI
    Panjang teks: 17816
[30/100] Mengambil: Pemahaman bahasa alami
    Panjang teks: 2252
[31/100] Mengambil: Pengenalan tulisan tangan
    Panjang teks: 14641
[32/100] Mengambil: Representasi dan Penalaran Pengetahuan
    Panjang teks: 16218
[33/100] Mengambil: Sistem pakar
    Panjang teks: 4352
[34/100] Mengambil: Stable Diffusion
    Panjang teks: 19970
[35/100] Mengambil: Unit pemroses grafis
    Panjang teks: 13692
[36/100] Mengambil: Visi komputer
429 untuk 'Visi komputer'. Menunggu 33 detik...
    Panjang teks: 13487
[37/100] Mengambil: Ilmu komputer
    Panjang teks: 16597
[38/100] Mengambil: Algoritma pencarian
    Panjang teks: 7799
[39/100] Mengambil: Aljabar Boole
    Panjang teks: 2731
[40/100] Mengambil: Analisis leksikal
    Panjang teks: 2045
[41/100] Mengambil: Bahasa pemrograman domain khusus
    Panjang teks: 25549
[42/100] Mengambil: Diagram alir data
    Panjang teks: 3513
[43/100] Mengambil: Hukum Moore
    Panjang teks: 13824
[44/100] Mengambil: Ilmu data
    Panjang teks: 4829
[45/100] Mengambil: Kernel (ilmu komputer)
    Panjang teks: 9007
[46/100] Mengambil: Kode
429 untuk 'Kode'. Menunggu 35 detik...
    Panjang teks: 7304
[47/100] Mengambil: NURBS
    Panjang teks: 2304
[48/100] Mengambil: Operasi ternary
    Panjang teks: 4390
[49/100] Mengambil: Penambangan data pendidikan
    Panjang teks: 21685
[50/100] Mengambil: Pohon urai
    Panjang teks: 3245
[51/100] Mengambil: Pola rancangan
    Panjang teks: 3469
[52/100] Mengambil: Pola serangan
    Panjang teks: 7999
[53/100] Mengambil: Simulasi komputer
    Panjang teks: 2119
[54/100] Mengambil: Pengolahan data
    Panjang teks: 2335
[55/100] Mengambil: Modus (statistika)
    Panjang teks: 3749
[56/100] Mengambil: Pengolahan data elektronik
429 untuk 'Pengolahan data elektronik'. Menunggu 35 detik...
    Panjang teks: 3681
[57/100] Mengambil: Manajemen data
    Panjang teks: 2016
[58/100] Mengambil: Abstraksi (ilmu komputer)
    Panjang teks: 2645
[59/100] Mengambil: Data tertaut
    Panjang teks: 4567
[60/100] Mengambil: Injeksi SQL
    Panjang teks: 11673
[61/100] Mengambil: Inteligensi bisnis
    Panjang teks: 32730
[62/100] Mengambil: Kolaborasi data
    Panjang teks: 3717
[63/100] Mengambil: Mahadata
    Panjang teks: 15573
[64/100] Mengambil: Manajemen pusat data
    Panjang teks: 12871
[65/100] Mengambil: Normalisasi pangkalan data
    Panjang teks: 2115
[66/100] Mengambil: Open Database Connectivity
429 untuk 'Open Database Connectivity'. Menunggu 36 detik...
    Panjang teks: 2424
[67/100] Mengambil: Pangkalan data berorientasi dokumen
    Panjang teks: 14563
[68/100] Mengambil: Pemrosesan analitik daring
    Panjang teks: 3098
[69/100] Mengambil: Pemulihan data
    Panjang teks: 19965
[70/100] Mengambil: Penggalian data
    Panjang teks: 6134
[71/100] Mengambil: Semafor (pemrograman)
    Panjang teks: 5169
[72/100] Mengambil: Transaksi basis data
    Panjang teks: 9500
[73/100] Mengambil: Teknologi informasi
    Panjang teks: 33395
[74/100] Mengambil: Akselerasi perangkat keras
    Panjang teks: 5042
[75/100] Mengambil: Arsitektur informasi
    Panjang teks: 5618
[76/100] Mengambil: BIOS
429 untuk 'BIOS'. Menunggu 36 detik...
    Panjang teks: 9541
[77/100] Mengambil: Deep Web
    Panjang teks: 3464
[78/100] Mengambil: Enkripsi surel
    Panjang teks: 8189
[79/100] Mengambil: Etika informasi
    Panjang teks: 6646
[80/100] Mengambil: Etika siber
    Panjang teks: 3525
[81/100] Mengambil: General protection fault
    Panjang teks: 4705
[82/100] Mengambil: Jaringan komputer
    Panjang teks: 12067
[83/100] Mengambil: Kolaborasi awan
    Panjang teks: 8392
[84/100] Mengambil: Konversi data
    Panjang teks: 3250
[85/100] Mengambil: Layanan elektronik
    Panjang teks: 27780
[86/100] Mengambil: Mode transfer asinkron
429 untuk 'Mode transfer asinkron'. Menunggu 36 detik...
    Panjang teks: 3159
[87/100] Mengambil: Pemasaran Internet
    Panjang teks: 2766
[88/100] Mengambil: Penggalian web
    Panjang teks: 2499
[89/100] Mengambil: Perangkat lunak enkripsi
    Panjang teks: 5921
[90/100] Mengambil: Perdagangan elektronik
    Panjang teks: 5949
[91/100] Mengambil: Permasalahan pada komputasi awan
    Panjang teks: 7521
[92/100] Mengambil: Pertukaran data elektronik
    Panjang teks: 5715
[93/100] Mengambil: Teknologi informasi komunikasi
    Panjang teks: 10560
[94/100] Mengambil: Transformasi digital
    Panjang teks: 12731
[95/100] Mengambil: WiMAX
    Panjang teks: 15810
[96/100] Mengambil: XDSL
429 untuk 'XDSL'. Menunggu 36 detik...
    Panjang teks: 3879
[97/100] Mengambil: Asymmetric digital subscriber line
    Panjang teks: 5417
[98/100] Mengambil: Internet untuk Segala
    Panjang teks: 23434
[99/100] Mengambil: Keamanan jaringan
    Panjang teks: 6834
[100/100] Mengambil: Peramban web
    Panjang teks: 8114

Buat DataFrame API

In [ ]:
df_api = pd.DataFrame(api_articles)

print(df_api.shape)
print(df_api.head())

(100, 2)
               Judul                                           API_Text
0     Algoritma bias  Algoritma bias menggambarkan galat sistematis ...
1  Algoritma Lanczos  Algoritma Lanczos adalah algoritma iteratif ad...
2              ASCII  (ASCII) singkatan dari American Standard Code ...
3      Karakter null  Karakter null (atau bita null), disingkat NUL ...
4    Komputasi optis  Komputasi optis adalah penggunaan foton yang d...

Validasi hasil API

In [ ]:
print("Jumlah artikel:", len(df_api))
print("Judul unik:", df_api["Judul"].nunique())
print("Teks kosong:", (df_api["API_Text"].str.len() == 0).sum())
print("Teks null:", df_api["API_Text"].isna().sum())

Jumlah artikel: 100
Judul unik: 100
Teks kosong: 0
Teks null: 0

In [ ]:
df_api["Panjang_API"] = df_api["API_Text"].str.len()

print(df_api["Panjang_API"].describe())

count      100.000000
mean      8482.050000
std       6945.305493
min       1598.000000
25%       3467.750000
50%       5845.500000
75%      12115.250000
max      33395.000000
Name: Panjang_API, dtype: float64

### Extracting hasil scraping API to .csv

In [112]:
df_api_export = df_api[['Judul', 'API_Text']].copy()

df_api_export['topik'] = df_api_export['Judul'].map(kategori_final)

df_api_export.columns = ['judul', 'teks', 'topik']

df_api_export.insert(0, 'no', range(1, len(df_api_export) + 1))

df_api_export.to_csv('hasil_scraping_api.csv', index=False)

print("Berhasil menyimpan df_api dengan kolom topik ke 'hasil_scraping_api.csv'!")
print(df_api_export.head())

Berhasil menyimpan df_api dengan kolom topik ke 'hasil_scraping_api.csv'!
   no              judul                                               teks  \
0   1     Algoritma bias  Algoritma bias menggambarkan galat sistematis ...
1   2  Algoritma Lanczos  Algoritma Lanczos adalah algoritma iteratif ad...
2   3              ASCII  (ASCII) singkatan dari American Standard Code ...
3   4      Karakter null  Karakter null (atau bita null), disingkat NUL ...
4   5    Komputasi optis  Komputasi optis adalah penggunaan foton yang d...

              topik
0  Computer Science
1  Computer Science
2  Computer Science
3  Computer Science
4  Computer Science

## Gabungan HTTP + API

In [ ]:
df_compare = df_final.merge(
    df_api,
    on="Judul",
    how="inner",
    validate="one_to_one"
)

In [ ]:
print(df_compare.shape)
print(df_compare.columns)

(100, 10)
Index(['Judul', 'URL', 'Overview_Isi', 'Tanggal_Suntingan', 'Penerbit',
       'Panjang_Teks', 'Topik_Sementara', 'Topik', 'API_Text', 'Panjang_API'],
      dtype='object')

In [ ]:
print("Jumlah data HTTP :", len(df_final))
print("Jumlah data API  :", len(df_api))
print("Jumlah hasil merge:", len(df_compare))
print("Judul unik hasil merge:", df_compare["Judul"].nunique())

Jumlah data HTTP : 100
Jumlah data API  : 100
Jumlah hasil merge: 100
Judul unik hasil merge: 100

In [ ]:
df_compare[
    [
        "Judul",
        "Topik",
        "Panjang_Teks",
        "Panjang_API"
    ]
].head(10)

                     Judul             Topik  Panjang_Teks  Panjang_API
0           Algoritma bias  Computer Science          9968         9922
1        Algoritma Lanczos  Computer Science         10448        24279
2                    ASCII  Computer Science          2153         2381
3            Karakter null  Computer Science          1762         1768
4          Komputasi optis  Computer Science          1552         1598
5  Membangkitkan Kombinasi  Computer Science          1516         3260
6    Komputasi neuromorfik  Computer Science          1598         2464
7            Teori otomata  Computer Science          1972         6619
8        Kecerdasan buatan                AI          7925        11028
9              Agen otonom                AI          2025         2375

In [ ]:
df_compare["Selisih_Panjang"] = (
    df_compare["Panjang_API"]
    - df_compare["Panjang_Teks"]
)

In [ ]:
df_compare[
    [
        "Judul",
        "Topik",
        "Panjang_Teks",
        "Panjang_API",
        "Selisih_Panjang"
    ]
].head(10)

,Judul,Topik,Panjang_Teks,Panjang_API,Selisih_Panjang
0,Algoritma bias,Computer Science,9968,9922,-46
1,Algoritma Lanczos,Computer Science,10448,24279,13831
2,ASCII,Computer Science,2153,2381,228
3,Karakter null,Computer Science,1762,1768,6
4,Komputasi optis,Computer Science,1552,1598,46
5,Membangkitkan Kombinasi,Computer Science,1516,3260,1744
6,Komputasi neuromorfik,Computer Science,1598,2464,866
7,Teori otomata,Computer Science,1972,6619,4647
8,Kecerdasan buatan,AI,7925,11028,3103
9,Agen otonom,AI,2025,2375,350

*Perbandingan Panjang Teks HTTP dan API*

Perbandingan dilakukan dengan menghitung selisih panjang teks antara hasil ekstraksi HTTP dan hasil ekstraksi API. Nilai positif menunjukkan bahwa teks hasil API lebih panjang, sedangkan nilai negatif menunjukkan bahwa teks hasil HTTP lebih panjang.

In [ ]:
print("Rata-rata panjang HTTP:",
      df_compare["Panjang_Teks"].mean())

print("Rata-rata panjang API:",
      df_compare["Panjang_API"].mean())

print("Rata-rata selisih:",
      df_compare["Selisih_Panjang"].mean())

Rata-rata panjang HTTP: 6638.64
Rata-rata panjang API: 8482.05
Rata-rata selisih: 1843.41

### Extracting hasil compare HTTP API to .csv

In [ ]:
df_compare_export = df_compare[['Judul', 'API_Text', 'Overview_Isi', 'Topik']].copy()

df_compare_export.columns = ['judul', 'teks_api', 'teks_html', 'topik']

df_compare_export.insert(0, 'no', range(1, len(df_compare_export) + 1))

df_compare_export.to_csv('hasil_scraping_compare.csv', index=False)

print("Berhasil menyimpan data df_compare ke 'hasil_scraping_compare.csv'!")
print(df_compare_export.head())

Berhasil menyimpan data df_compare ke 'hasil_scraping_compare.csv'!
   no              judul                                           teks_api  \
0   1     Algoritma bias  Algoritma bias menggambarkan galat sistematis ...
1   2  Algoritma Lanczos  Algoritma Lanczos adalah algoritma iteratif ad...
2   3              ASCII  (ASCII) singkatan dari American Standard Code ...
3   4      Karakter null  Karakter null (atau bita null), disingkat NUL ...
4   5    Komputasi optis  Komputasi optis adalah penggunaan foton yang d...

                                           teks_html             topik
0  Algoritma bias menggambarkan galat sistematis ...  Computer Science
1  Algoritma Lanczos adalah algoritma iteratif ad...  Computer Science
2  (ASCII) singkatan dari American Standard Code ...  Computer Science
3  Karakter null (atau bita null), disingkat NUL ...  Computer Science
4  Komputasi optis adalah penggunaan foton yang d...  Computer Science